### ISSUE TITLE
"Edit advanced config?" dialog could be improved

### ISSUE THREAD

**Issue by SigmaBonder** [chenxiaolong/RSAF#10]
Currently, the prompt asking user to decide if they want to configure advanced options is treated like any other, with a "Use default value" toggle and radio buttons behind.
<details><summary>Screenshot</summary>
<img alt="advanced config dialog" src="https://github.com/chenxiaolong/RSAF/assets/116167153/7fccc33c-3938-4c2c-a72b-797bc8a78034"/>
</details>

I think that a simple dialog window with "Yes" and "No" buttons instead of "Cancel", "Next", toggle and radio select buttons would be a much better fit here.

**Comment by chenxiaolong** [comment]
After #14, it's a little simpler now with the toggle switch gone: [Screenshot_20230620-004051](https://github.com/chenxiaolong/RSAF/assets/646253/a2f55814-5342-44c3-9f18-1c2b1902b6a0). Still not ideal though.

I think your suggestion is a good idea, but I probably won't change it for now. rclone presents this question in the same way as all other questions and I'd prefer not to add a special case for a single question. We have to do that for the "authorize" question for cloud providers, which is unfortunately already quite painful/annoying to implement.
