### ISSUE TITLE
Concern regarding "Allow Android backups"

### ISSUE THREAD

**Issue by CodeCracker-oss** [chenxiaolong/RSAF#100]
Hello,

I am not sure how much developers have sort of control over android backup mechanism, from what I knew if this allowBackup was set to true it would allow android native backup feature or adb to backup app private data.

My concern is ever having this done due to sensitive nature of my rclone.conf file. (My lack of trust in cloud storage, especially google, hence why I use crypt).

When this feature is disabled (it's default), does it basically just exclude rclone.conf from this backup or act as if this value is false preventing all settings from being backed up?

I always though this was basically an all or nothing, either allowed to be backed up or not. Didn't know if apps could have any level of control over it.

Could you shed some further light on this?

Thank you :)

**Comment by chenxiaolong** [comment]
There are two backup mechanisms in Android when `allowBackup` is set to true: auto-backup and key-value backup. For auto-backup, the app developer specifies a list of files to back up and Android will automatically copy those files. For key-value backup, nothing is automatic and the app needs to actively send specific data to Android for it to be backed up.

RSAF uses key-value backup. When the `Allow Android backups` option is turned off, RSAF will not send any data to Android (neither `rclone.conf` nor any global settings). Android still creates a backup, but it will be completely empty. I could potentially make it only exclude `rclone.conf`, but I've chosen not to do so to make the backup code simpler.
