### ISSUE TITLE
View Logs / can't see any files

### ISSUE THREAD

**Issue by jstride** [chenxiaolong/RSAF#102]
Is there any way to see logs? I have a remote (s3) yet when I view the bucket/folder in Files it is empty (I have imported the config and know that rclone on other machines can list/view the folder). Am I missing something?

**Comment by chenxiaolong** [comment]
Yes, if you long press RSAF's version number, you'll get an option to save the logs.

**Comment by jstride** [comment]
Would any of these errors be critical/stop it showing the list of files (if I create a folder in my S3 - cloudflare it appears on cloudflare, I don't see any existing files though).

[logcat.log](https://github.com/user-attachments/files/17709785/logcat.log)

**Comment by chenxiaolong** [comment]
Can you try reproducing the problem after enabling the debug mode (long press) but before saving the logs? The file you uploaded doesn't have any access logs. Access logs only start showing up after the debug mode is enabled.

The log lines you are looking for are the ones that contain `RcloneProvider`. For listing files, the line will also contain `queryChildDocuments`. For example:

```
D/RcloneProvider( 3216): queryChildDocuments(test-smb:, null, _display_name ASC)
                                             ^^^^^^^^^
                                 The exact rclone path being accessed
```

It may be helpful to enable the `Verbose rclone logs` option too, but don't upload any logs created afterwards until it's disabled again and the device is rebooted. (rclone's verbose logs likely include credentials.)

---

Also, it might be worth testing on a non-Android device if you see the existing files when mounting the bucket with:

```
rclone mount <bucket>: /some/mount/path --vfs-cache-mode writes
```

`rclone mount` is equivalent to how RSAF interacts with rclone.

**Comment by jstride** [comment]
I just see the following:

`11-14 20:35:03.139 25102 25138 I GoLog   : 2024/11/14 12:35:03 DEBUG : fs cache: switching user supplied name "CF:" for canonical name "cloudflare:jake"
11-14 20:35:03.139 25102 25138 I GoLog   : 2024/11/14 12:35:03 NOTICE: CF:: No VFS caching preference. Enabling VFS caching
11-14 20:35:03.139 25102 25138 I GoLog   : 2024/11/14 12:35:03 DEBUG : : OpenFile: flags=O_RDONLY, perm=----------
11-14 20:35:03.139 25102 25138 I GoLog   : 2024/11/14 12:35:03 DEBUG : : >OpenFile: fd=/ (r), err=<nil>
11-14 20:35:03.428 25102 25295 I GoLog   : 2024/11/14 12:35:03 INFO  : vfs cache: cleaned: objects 0 (was 0) in use 0, to upload 0, uploading 0, total size 0 (was 0)
11-14 20:35:06.166 25102 25138 D RcloneProvider: queryChildDocuments(CF:, null, _display_name ASC)
11-14 20:35:06.167 25102 25138 I GoLog   : 2024/11/14 12:35:06 DEBUG : rc: "config/dump": with parameters map[]`

I have tried the config on another machine and rclone ls CF: works and gives a listing as expected

**Comment by jstride** [comment]
I just see the following:

`11-14 20:35:03.139 25102 25138 I GoLog   : 2024/11/14 12:35:03 DEBUG : fs cache: switching user supplied name "CF:" for canonical name "cloudflare:jake"
11-14 20:35:03.139 25102 25138 I GoLog   : 2024/11/14 12:35:03 NOTICE: CF:: No VFS caching preference. Enabling VFS caching
11-14 20:35:03.139 25102 25138 I GoLog   : 2024/11/14 12:35:03 DEBUG : : OpenFile: flags=O_RDONLY, perm=----------
11-14 20:35:03.139 25102 25138 I GoLog   : 2024/11/14 12:35:03 DEBUG : : >OpenFile: fd=/ (r), err=<nil>
11-14 20:35:03.428 25102 25295 I GoLog   : 2024/11/14 12:35:03 INFO  : vfs cache: cleaned: objects 0 (was 0) in use 0, to upload 0, uploading 0, total size 0 (was 0)
11-14 20:35:06.166 25102 25138 D RcloneProvider: queryChildDocuments(CF:, null, _display_name ASC)
11-14 20:35:06.167 25102 25138 I GoLog   : 2024/11/14 12:35:06 DEBUG : rc: "config/dump": with parameters map[]`

**Comment by jstride** [comment]
Let's put it down to user error - restarting made it work.
