### ISSUE TITLE
Open Wiki to document apps playing nicely with RSAF

### ISSUE THREAD

**Issue by neingeist** [chenxiaolong/RSAF#112]
I love RSAF! It lets me easily access my files on my NAS via SMB and on other cloud services!

I've been testing a number of apps (file managers, players) to find the ones that work nicely with RSAF, and now I'm looking for a way to share my findings. Would you consider opening the Wiki here in the GitHub project for this?

**Comment by chenxiaolong** [comment]
Glad you like RSAF and sure thing! I've enabled the wiki and changed the permissions to allow any user to add pages: https://github.com/chenxiaolong/RSAF/wiki

**Comment by neingeist** [comment]
Awesome! I've created this page to list the apps I found working well with RSAF:

https://github.com/chenxiaolong/RSAF/wiki/Apps-that-play-well-with-RSAF
