### ISSUE TITLE
[FR] Option to hide remotes

### ISSUE THREAD

**Issue by DarremMolko** [chenxiaolong/RSAF#16]
I have three remotes and I have combined them into one, I'd like to hide them from appearing in the DocumentsUI. I know I can "delete" the remotes but if I do that the "combine" remote stops working.

Here's an screenshot, I'd like to hide ko3, nf and sp
![Screenshot_20230623-120551](https://github.com/chenxiaolong/RSAF/assets/70179709/398657f7-2e63-4605-be24-5364ad739337)
I assume there could be a button here to Hide/Unhide
![Screenshot_20230623-121754](https://github.com/chenxiaolong/RSAF/assets/70179709/bb1053b6-a3f3-4c62-901c-49af21e1d6ad)

**Comment by chenxiaolong** [comment]
I like this idea. I've implemented it in #17, which will be part of version 1.5.

**Comment by chenxiaolong** [comment]
I pushed an additional fix in #19 (included in version 1.6) to fix a hang when hiding certain cloud remotes.

**Comment by DarremMolko** [comment]
Hi Andrew. I never managed to make my "combine" remote work. It is not really a problem but maybe there is something that can be done to fix it. I tried again a few moments ago after updating RSAF and the app crashed, here are the logs:
[crash.log](https://github.com/chenxiaolong/RSAF/files/11927687/crash.log)

**Comment by chenxiaolong** [comment]
Thanks for the logs! Any chance the crashed happened when hitting Cancel in the Configure Remote dialog? I think I may have found a possible issue related to that which only happens on Android <13.

Regarding `combine` not working, I'm seeing this error in the logs:

> combine can't point to an empty upstream - check the value of the upstreams setting

Can you post the value you have set for that option?

**Comment by DarremMolko** [comment]
> Thanks for the logs! Any chance the crashed happened when hitting Cancel in the Configure Remote dialog? I think I may have found a possible issue related to that which only happens on Android <13.
> 
> Regarding `combine` not working, I'm seeing this error in the logs:
> 
> ```
> combine can't point to an empty upstream - check the value of the upstreams setting
> ```
> 
> Can you post the value you have set for that option?

I'm so sorry for wasting your time, it was my fault all along. I misspelled something in my rclone.conf and that's why RSAF couldn't load it.
Regarding the crash, it is indeed related to the Cancel button, just confirmed it, this is the crash log:
[crash2.log](https://github.com/chenxiaolong/RSAF/files/11927718/crash2.log)

**Comment by chenxiaolong** [comment]
No worries! It's not a waste of my time at all--always happy to help troubleshoot.

I'll work on the Cancel button issue. It should be a really quick fix.

**Comment by chenxiaolong** [comment]
Fixed in #24 (included in version 1.9)

**Comment by DarremMolko** [comment]
That was indeed quick. Thank you so much for all your hard work Andrew.
