### ISSUE TITLE
RSAF has more bugs

### ISSUE THREAD

**Issue by JulianICE08935** [chenxiaolong/RSAF#22]
when you close the app and then go to the files app the files app suddenly says "content could not be loaded right now" and when i start the app again android says "RSAF not responding"

![Screenshot_20230701-093915.png](https://github.com/chenxiaolong/RSAF/assets/106862754/30022186-a9d3-46c1-9e13-6bcff8a968a5)

![Screenshot_20230701-093649.png](https://github.com/chenxiaolong/RSAF/assets/106862754/93a3c439-55f7-473f-a707-5d13fb8a2751)

![Screenshot_20230701-093659.png](https://github.com/chenxiaolong/RSAF/assets/106862754/924f0ed7-44ea-44bc-95d8-8031a4f13d64)

**Comment by chenxiaolong** [comment]
Hmm, I'm not able to reproduce this. Can you upload the latest `crash.log` from `/sdcard/Android/data/com.chiller3.rsaf/files`?

**Comment by JulianICE08935** [comment]
no crash.log is created for me because it was already hanging up and hadn't reacted to anything and the processes hung up due to RSAF

**Comment by JulianICE08935** [comment]
![Screenshot_20230701-160924.png](https://github.com/chenxiaolong/RSAF/assets/106862754/739a859c-6f66-45f1-b1ef-14f07a6cc8ae)

![Screenshot_20230701-160929.png](https://github.com/chenxiaolong/RSAF/assets/106862754/430695ed-e01d-4bff-93cf-491612b8f2e7)

**Comment by JulianICE08935** [comment]
the crash.log could not be created because it was also true when starting and it cannot run in the background, whether with or without battery optimization, RSAF does not run in the background

**Comment by JulianICE08935** [comment]
if you don't get any further with the information and it happens to several people and then maybe everyone complains then it's your own fault
