### ISSUE TITLE
Feature request: disabling volumes, app lock

### ISSUE THREAD

**Issue by anedroid** [chenxiaolong/RSAF#27]
Option to disable volumes, making any access attempt failed (might be an improvement to hiding volumes from the UI). This would be useful if I have a volume with sensitive files that I need to temporarily hide.

Option to require authorization (e.g. fingerprint, PIN, etc.) to open the app to protect the configuration from reading credentials or unauthorized changes.

**Comment by chenxiaolong** [comment]
> (might be an improvement to hiding volumes from the UI)

Agreed. The intention of the `Hide from DocumentsUI` option is to prevent external access anyway. It makes sense to extend that to block all access that might've already been granted prior to hiding. This should be really easy to implement.
