### ISSUE TITLE
Fix: local storage

### ISSUE THREAD

**Issue by anedroid** [chenxiaolong/RSAF#28]
RSAF does not have r/w external storage permission, cannot access local storage to use transparent backends like crypt, compress, chunker or combine.

**Comment by chenxiaolong** [comment]
I'll consider adding support for this. Unfortunately, it'll have to be an all-or-nothing solution. RSAF either has access to all local files (via the "all files" permission) or none at all.

The normal method of using the system file picker to grant access to a specific directory doesn't work with native code, like rclone. It's a known Android issue and likely won't be fixed any time soon: https://issuetracker.google.com/issues/199091106.
