### ISSUE TITLE
Bug: nothing happens when adding "drive" backend after authorizing rclone app in browser and returning to RSAF

### ISSUE THREAD

**Issue by soredake** [chenxiaolong/RSAF#55]
After authorizing app in browser, I see this:
![image](https://github.com/chenxiaolong/RSAF/assets/5204968/ef087def-5159-4899-8f5d-0eb1b040e546)

And after returning to app, I see this:
![image](https://github.com/chenxiaolong/RSAF/assets/5204968/81531a7e-a09a-484f-8ab0-d3c8832e56c5)

**Comment by chenxiaolong** [comment]
Thanks for reporting this. I'm able to reproduce this (sometimes).

The rclone authorization flow in RSAF is very finicky. It relies on parsing logs from `rclone authorize` because there's no other way to obtain the token after a successful login. The problem you're seeing is caused by a timing issue and happens if rclone logs the token after a short delay (instead of immediately).

I believe I found a decent way to fix this. I'll upload a test build shortly.

**Comment by chenxiaolong** [comment]
This should be fixed by #56. Please give this test build a try:

* arm64-v8a: https://files.pub.chiller3.com/issues/RSAF/issue55/RSAF-1.23.r2.g7e3c1e3-arm64-v8a-release.apk
* armeabi-v7a: https://files.pub.chiller3.com/issues/RSAF/issue55/RSAF-1.23.r2.g7e3c1e3-armeabi-v7a-release.apk
* x86: https://files.pub.chiller3.com/issues/RSAF/issue55/RSAF-1.23.r2.g7e3c1e3-x86-release.apk
* x86_64: https://files.pub.chiller3.com/issues/RSAF/issue55/RSAF-1.23.r2.g7e3c1e3-x86_64-release.apk

These are signed with the same key as the release builds. When you install it, it should update your existing RSAF app.

**Comment by soredake** [comment]
Yes, this pr fixes this problem, thank you!

**Comment by chenxiaolong** [comment]
Great, thanks for testing! I'll merge the PR and release a new version.

**Comment by viche12345** [comment]
Unfortunately, this may have regressed. I'm still able to reproduce this with version 3.3. Are you able to reproduce this @chenxiaolong?

Pixel 7 Pro
Android 15

**Comment by chenxiaolong** [comment]
That's really strange. Version 3.3 should behave exactly like your own build of 093ff7969c259268f6ed8bed6e4d4fd62eac1d88. Debug builds don't have any special behavior.

I'm not able to reproduce the issue with a Google Drive remote:

```
D/Authorizer(17711): Starting logcat
I/GoLog   (17711): Log marker for 'start': a*]y1W,Y;*v?pN5U8}+:%E9.xxIsEW /
W/libc    (18015): Access denied finding property "ro.debuggable"
D/Authorizer(17711): Starting authorize server for [drive]
I/GoLog   (17711): 2025/03/08 01:35:20 NOTICE: Make sure your Redirect URL is set to "http://127.0.0.1:53682/" in your custom config.
I/GoLog   (17711): 2025/03/08 01:35:20 NOTICE: Please go to the following link: http://127.0.0.1:53682/auth?state=Wz75EcLn3zjX6yLsIVmoLg
I/GoLog   (17711): 2025/03/08 01:35:20 NOTICE: Log in and authorize rclone for access
I/GoLog   (17711): 2025/03/08 01:35:20 NOTICE: Waiting for code...
I/GoLog   (17711): 2025/03/08 01:35:57 NOTICE: Got code
I/GoLog   (17711): Paste the following into your remote machine --->
I/GoLog   (17711): {"access_token":"<redacted>","token_type":"Bearer","refresh_token":"<redacted>","expiry":"2025-03-08T02:35:56.366642511Z"}
I/GoLog   (17711): <---End paste
D/Authorizer(17711): Stopped authorize server
D/Authorizer(17711): Stopped log parser
```

If it's consistently reproducible on the release version, could you grab the logcat after attempting to do the oauth2 authorization?

**Comment by viche12345** [comment]
Yep, I just repro'd it again on the release version. Got these logs:

```
03-08 09:51:05.903 18235 18271 D Authorizer: Starting logcat
03-08 09:51:05.908 18235 18271 I GoLog   : Log marker for 'start': nUoIABSIhG;O=cU1zG5oc$yZHj}Bo_ij
03-08 09:51:05.909 18235 18989 D Authorizer: Starting authorize server for [drive, eyJjbGllbnRfaWQiOiIxMDM0MzkxMjUzNzY3LTNmMWZkbDBwaGhha3FoaDRvZzJmczZkZDN0Y3VyYm51LmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29tIiwiY2xpZW50X3NlY3JldCI6IkdPQ1NQWC1SS1FETUZVajhXTTlCOTl0U3ZDcDU4VGhNZnhHIiwic2NvcGUiOiJkcml2ZSJ9]
03-08 09:51:05.912 18235 18989 I GoLog   : 2025/03/08 17:51:05 NOTICE: Make sure your Redirect URL is set to "http://127.0.0.1:53682/" in your custom config.
03-08 09:51:05.913 18235 18989 I GoLog   : 2025/03/08 17:51:05 NOTICE: Please go to the following link: http://127.0.0.1:53682/auth?state=nhVJp39kQPDtoiqTUaJgWQ
03-08 09:51:05.913 18235 18989 I GoLog   : 2025/03/08 17:51:05 NOTICE: Log in and authorize rclone for access
03-08 09:51:05.913 18235 18989 I GoLog   : 2025/03/08 17:51:05 NOTICE: Waiting for code...
03-08 09:51:05.909 18235 18235 W Thread-7: type=1400 audit(0.0:275979): avc:  denied  { read } for  name="somaxconn" dev="proc" ino=42221472 scontext=u:r:untrusted_app:s0:c94,c258,c512,c768 tcontext=u:object_r:proc_net:s0 tclass=file permissive=0 app=com.chiller3.rsaf
03-08 09:51:05.940 18235 18235 W WindowOnBackDispatcher: sendCancelIfRunning: isInProgress=false callback=androidx.activity.OnBackPressedDispatcher$Api34Impl$createOnBackAnimationCallback$1@f19ed82
03-08 09:51:05.960 18235 18235 W TextView: onProvideContentCaptureStructure(): calling assumeLayout()
03-08 09:51:05.960 18235 18235 W TextView: onProvideContentCaptureStructure(): calling assumeLayout()
03-08 09:51:09.892 18235 18235 D SettingsActivity: onPause()
03-08 09:51:10.644 18235 18235 D VRI[SettingsActivity]: visibilityChanged oldVisibility=true newVisibility=false
03-08 09:51:10.657 18235 18235 D VRI[SettingsActivity]: visibilityChanged oldVisibility=true newVisibility=false
03-08 09:51:10.657 18235 18235 D VRI[SettingsActivity]: visibilityChanged oldVisibility=true newVisibility=false
03-08 09:51:10.664 18235 18235 I AutofillManager: onInvisibleForAutofill(): expiringResponse
03-08 09:51:18.210 18235 18989 I GoLog   : 2025/03/08 17:51:18 NOTICE: Got code
03-08 09:51:18.216 18235 18989 W Authorizer: rbAuthorize error: failed to get token: Post "https://oauth2.googleapis.com/token": dial tcp: lookup oauth2.googleapis.com: no such host
03-08 09:51:18.216 18235 18989 D Authorizer: Stopped authorize server
03-08 09:51:30.644 18235 18235 D SettingsActivity: onResume()
03-08 09:51:30.645 18235 18235 D SettingsActivity: Top-level activity in stack is: ComponentInfo{com.chiller3.rsaf/com.chiller3.rsaf.settings.SettingsActivity}
03-08 09:51:30.645 18235 18235 D SettingsActivity: Covered by safe activity: false
03-08 09:51:30.645 18235 18235 D SettingsActivity: Updating view state: true
03-08 09:51:30.645 18235 18235 D SettingsActivity: Updating focusable/touchable state: true
03-08 09:51:30.687 18235 18235 E m.chiller3.rsaf: Invalid resource ID 0x00000000.
03-08 09:51:30.688 18235 18235 E m.chiller3.rsaf: Invalid resource ID 0x00000000.
03-08 09:51:30.688 18235 18235 E m.chiller3.rsaf: Invalid resource ID 0x00000000.
03-08 09:51:30.688 18235 18235 E m.chiller3.rsaf: Invalid resource ID 0x00000000.
03-08 09:51:30.688 18235 18235 E m.chiller3.rsaf: Invalid resource ID 0x00000000.
03-08 09:51:30.688 18235 18235 E m.chiller3.rsaf: Invalid resource ID 0x00000000.
03-08 09:51:30.688 18235 18235 E m.chiller3.rsaf: Invalid resource ID 0x00000000.
03-08 09:51:30.688 18235 18235 E m.chiller3.rsaf: Invalid resource ID 0x00000000.
03-08 09:51:30.688 18235 18235 E m.chiller3.rsaf: Invalid resource ID 0x00000000.
03-08 09:51:30.688 18235 18235 E m.chiller3.rsaf: Invalid resource ID 0x00000000.
03-08 09:51:30.688 18235 18235 E m.chiller3.rsaf: Invalid resource ID 0x00000000.
03-08 09:51:38.141 18235 18235 W WindowOnBackDispatcher: sendCancelIfRunning: isInProgress=false callback=android.app.Dialog$$ExternalSyntheticLambda2@b0554c1
03-08 09:51:38.141 18235 18273 I GoLog   : Log marker for 'cancel': 8{Sl6>Eq+{oJGdP1>{FK@t)r8xw*YRo8
03-08 09:51:38.143 18235 18271 D Authorizer: Stopped log parser
03-08 09:51:38.153 18235 18265 D HWUI    : endAllActiveAnimators on 0x79c9f81aa0 (RippleDrawable) with handle 0x7af9f220a0
03-08 09:51:38.163 18235 18273 W Authorizer: Error when cancelling authorize server: java.net.ConnectException: Failed to connect to localhost/127.0.0.1:53682
03-08 09:51:38.176 18235 18235 W WindowOnBackDispatcher: sendCancelIfRunning: isInProgress=false callback=androidx.activity.OnBackPressedDispatcher$Api34Impl$createOnBackAnimationCallback$1@f19ed82
```

Could this be a clue?
`W Authorizer: rbAuthorize error: failed to get token: Post "https://oauth2.googleapis.com/token": dial tcp: lookup oauth2.googleapis.com: no such host`

**Comment by viche12345** [comment]
Unfortunately I'm not using any VPN or custom DNS. Strange that the debug version works for me though.

Do you know of a way I can test this out to potentially isolate the issue? Maybe from a sample app or adb shell?

**Comment by chenxiaolong** [comment]
Maybe you could try adding an `http` remote with a URL like https://mirrors.kernel.org/fedora/. If something is up with DNS, I suspect that'll fail after trying to open the remote in the file manager.

**Comment by chenxiaolong** [comment]
Glad you were able to find a workaround!

I really have no idea what could cause this, especially if it's intermittent. I did take a look at how DNS resolving works in golang since I remember there being something odd. It can either use its own resolver (`GODEBUG=netdns=go` env var) or use the system resolver (`GODEBUG=netdns=cgo`). On Android though, golang only supports the system resolver, so it's not doing anything weird there.

**Comment by mrjo118** [comment]
@chenxiaolong I'm still getting this issue (happens every time) in v4.3. tested with both Box and OneDrive and the app waits indefinately for the authorization, even though it is completed in the browser. I'm using Android 16

**Comment by chenxiaolong** [comment]
@mrjo118 I've created a new issue for this in https://github.com/chenxiaolong/RSAF/issues/311. Let's continue discussion there
