### ISSUE TITLE
[SUGGESTION] Clarify disabling of battery optimization 

### ISSUE THREAD

**Issue by sand-bit** [chenxiaolong/RSAF#59]
Fantastic project here Andrew, RSAF is something that I've been looking for -- literally for years. It is remarkably bug free and worked on the first try.

I primarily use it to stream 4K HDR from a SFTP network mount.

I noticed an issue with this app on OnePlus devices (probably other vendor variants as well), and that was if you opened this app, opened a remote mount within the app, then opened a video using VLC from the app, the streaming would stop after like 10 seconds. I tried this multiple times with app restarts and it consistently happened.

After some minor debugging, I realized it was caused due to OnePlus battery optimizations, and disabling all of the optimizations caused the streaming to work again on OnePlus devices:
* Battery -> More Settings -> App battery management -> RSAF -> Allow background activity + Allow this app to launch other apps
* Battery -> More Settings -> Optimize battery use -> RSAF -> Don't optimize
* Locking the RSAF app by dragging it down in the app switcher

Not sure which change specifically caused it to start working again, but after these changes I was able to stream 4K HDR via VLC. 

I mention this because it may be something that should be mentioned in the README, that vendor specific battery optimizations may interfere with RSAF.

Btw I'd happily donate to this project if donation was an option, of course without any expectation of obligation.

**Comment by chenxiaolong** [comment]
Thanks for the info! I've added a link to https://dontkillmyapp.com/ in the README (0046f80f4cb379175b6478c4347f4b80db6a78eb). That site has instructions for how to disable battery optimizations for most vendors. It's unfortunate how many vendors seem to have a poor battery optimization implementation.

> Fantastic project here Andrew, RSAF is something that I've been looking for -- literally for years. It is remarkably bug free and worked on the first try.
> <...>
> Btw I'd happily donate to this project if donation was an option, of course without any expectation of obligation.

Glad you like RSAF! A kind message like this is more than enough.
