### ISSUE TITLE
Password-based remotes don't work

### ISSUE THREAD

**Issue by SigmaBonder** [chenxiaolong/RSAF#7]
[In the rclone config file, human-readable passwords have to be obscured.](https://rclone.org/commands/rclone_obscure/)
Currently, they don't seem to be, which results in this error when trying to use password-based remotes like SSH:
`input too short when revealing password - is it obscured?`
I hope I'm not exaggerating this issue here, as the only password-based remote I tested was SSH, but it seems reasonable to assume that the issue will be common to all of those.

**Comment by chenxiaolong** [comment]
Thanks, I'm able to reproduce this with SMB. I'll investigate.

**Comment by chenxiaolong** [comment]
Looks like this is a bug in rclone. I can reproduce it on the command line.

In one terminal:

```bash
rclone rcd --rc-no-auth
```

In another terminal:

```bash
rclone config create test smb --non-interactive --all
# Hostname
rclone config update test --non-interactive --continue --state "*all-set,0,false" --result hostname --all
# Username
rclone config update test --non-interactive --continue --state "*all-set,1,false" --result username --all
# Port number
rclone config update test --non-interactive --continue --state "*all-set,2,false" --all
# Password
rclone config update test --non-interactive --continue --state "*all-set,3,false" --result foobar --obscure --all
```

Resulting config:

```
$ cat ~/.config/rclone/rclone.conf
[test]
type = smb
host = hostname
user = username
port =
pass = foobar
```

Seems like rclone doesn't respect the `--obscure` flag in the configuration API. (RSAF uses the same option, but programmatically.) I'll see if I can work around this.

**Comment by chenxiaolong** [comment]
I submitted an upstream bug report for this: https://github.com/rclone/rclone/issues/7069 I'll make RSAF explicitly obscure the password in the meantime.
