### ISSUE TITLE
Flexible prompt size is problematic when user has to configure a "deep" option

### ISSUE THREAD

**Issue by SigmaBonder** [chenxiaolong/RSAF#9]
When a user needs to change an existing remote's option that is far in the prompt chain, they need to select "Next" many times in order to get there. In CLI it would be simple, as it just requires pressing Enter to keep the current config value and go to the next one. On a touch screen, the default dialog behavior of adjusting its size to contents invites the user for a whack-a-mole game. It could be better to make the dialog always occupy full screen, even if the empty space may not be visually appealing.

Additionally, some way to go back to the previous prompt would be very useful in this scenario (in case the user happens to click "Next" one time too many).

**Comment by chenxiaolong** [comment]
Good point about the whack-a-mole. I've added a new option in #15 that makes all dialog boxes show up at the bottom of the screen. This should keep the reset/cancel/next buttons always in the same place.

> Additionally, some way to go back to the previous prompt would be very useful in this scenario (in case the user happens to click "Next" one time too many).

This is unfortunately not possible with rclone's interactive configuration API.
